server:
  name: "sgx-notary-server"
  host: "0.0.0.0"
  port: 7047

notarization:
  max-transcript-size: 16384

tls:
  enabled: true
  private-key-pem-path: "../common/fixture/tls/privkey1.pem"
  certificate-pem-path: "../common/fixture/tls/cert1.pem"

notary-key:
  private-key-pem-path: "./fixture/notary/notary.key"
  public-key-pem-path: "./fixture/notary/notary.pub"

tracing:
  default-level: DEBUG

logging:
  level: DEBUG

authorization:
  enabled: false
  whitelist-csv-path: "./fixture/auth/whitelist.csv"
