[package]
name = "sgx-notary-server"
version = "0.1.0-alpha.3"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6.8"
tracing = "0.1"
structopt = "0.3.26"
notary-server = { git = "https://github.com/tlsnotary/tlsn.git", tag = "v0.1.0-alpha.4", package = "notary-server" }

